name: ci_foxy

on:
  push:
    branches:
      - "foxy"
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    if: |
      ((github.event.action == 'labeled') && (github.event.label.name == 'TESTING')) ||
      ((github.event.action == 'synchronize') && contains(github.event.pull_request.labels.*.name, 'TESTING'))
    container:
      image: osrf/ros:${{ matrix.ros_distribution }}-desktop
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        ros_distribution: [foxy]
    steps:
      - name: Install OpenVINO
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          echo "deb https://apt.repos.intel.com/openvino/2024 ubuntu20 main" | sudo tee /etc/apt/sources.list.d/intel-openvino-2024.list
          sudo apt-get update
          sudo apt install -y openvino-2024.3.0
      - uses: actions/checkout@v4
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
      - name: Build and Test
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: ${{ matrix.ros_distribution }}
          skip-tests: true
          extra-cmake-args: "-DYOLOX_USE_OPENVINO=True"